import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import gsap from "gsap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>3legant</title>
      <body className={inter.className}>
        <>
          <Header />
          <div className="pt-16">
          {children}
          </div>
          <Footer />
          <ToastContainer
            position="top-center"
            autoClose={1500}
            progressClassName={"text-red"}
          />
        </>
      </body>
    </html>
  );
}
